config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :contacts do
    resources :csv_files
  end

  resources :contacts

  root to: 'contacts/csv_files#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  VALID_NAME_REGEX = /\A[a-zA-Z -]+\z/
  VALID_DOB_REGEX = %r{\b\d{4}([-/ ])\d{1,2}\1\d{1,2}\b}
  VALID_PHONE_REGEX = /\(?\+?[0-9]{2}\)\s?[0-9]{3}(\ |-)[0-9]{3}(\s|-)[0-9]{2}(\s|-)[0-9]{2}/

  belongs_to :contacts_csv_file, class_name: 'Contacts::CsvFile', foreign_key: :contacts_csv_file_id
  has_one :user, through: :contacts_csv_file
  has_many :credit_cards

  accepts_nested_attributes_for :credit_cards

  validates :address, presence: true
  validates :name, presence: true, format: { with: VALID_NAME_REGEX }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :dob, presence: true, format: { with: VALID_DOB_REGEX }
  validates :phone, presence: true, format: { with: VALID_PHONE_REGEX }
end

app/models/contacts.rb
module Contacts
  def self.table_name_prefix
    'contacts_'
  end
end

app/models/contacts/csv_file.rb
# frozen_string_literal: true

module Contacts
  class CsvFile < ApplicationRecord
    self.table_name = 'contacts_csv_files'

    has_one_attached :data
    belongs_to :user

    has_many :contacts, foreign_key: :contacts_csv_file_id

    enum status: {
      on_hold: 0,
      processing: 1,
      failed: 2,
      finished: 3
    }

    ACCEPTABLE_HEADERS = %w[name date_of_birth phone email address].freeze
    ACCEPTABLE_TYPES = ['text/csv'].freeze

    MAX_FILE_SIZE = 10.megabytes

    validates :name, :data, presence: true

    private

    def file_format
      errors.add(:base, 'invalid type') unless ACCEPTABLE_TYPES.include?(data.content_type)
    end

    def valid_file_size
      errors.add(:base, 'too large') if data.attached? && data.blob.byte_size > MAX_FILE_SIZE
    end

    def valid_headers
      return unless attachment_changes['data']&.attachable.present?

      begin
        headers = CSV.open(attachment_changes['data'].attachable, 'r', &:first)

        errors.add(:base, 'invalid_headers') unless headers.sort == ACCEPTABLE_HEADERS.sort
      rescue CSV::MalformedCSVError
        errors.add(:base, 'malformed file structure')
      end
    end
  end
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  BRANDS_REGEX = {
    visa: /^4[0-9]{12}(?:[0-9]{3})?$/,
    master_card: /^(?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)[0-9]{12}$/,
    american_express: /^3[47][0-9]{13}$/,
    diners_club: /^3(?:0[0-5]|[68][0-9])[0-9]{11}$/,
    discover: /^6(?:011|5[0-9]{2})[0-9]{12}$/,
    jcb: /^(?:2131|1800|35\d{3})\d{11}$/
  }.freeze

  belongs_to :contact

  attr_accessor :card_number

  validates :card_number, presence: true, length: { minimum: 10, maximum: 19 }
  validates :last_four, presence: true
  validates :franchise, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :csv_files, class_name: 'Contacts::CsvFile'
  has_many :contacts, through: :csv_files
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts/csv_files_controller.rb
module Contacts
  class CsvFilesController < ApplicationController
    def index
      @contacts_csv_files = Contacts::CsvFile.all
    end

    def show
      @contacts_csv_file = Contacts::CsvFile.find(params[:id])
    end

    def new
      @contacts_csv_file = Contacts::CsvFile.new
    end

    def create
      @csv_file = Contacts::CsvFile.new(name: contacts_csv_file_params['data']&.original_filename,
                                        data: contacts_csv_file_params['data'],
                                        user_id: current_user.id)

      if @csv_file.save
        Contacts::CsvFileJob.perform_later @csv_file.id
        redirect_to contacts_csv_files_url, notice: 'The file was successfully uploaded and will be processed soon.'
      else
        render :new
      end
    end

    private

    def contacts_csv_file_params
      params.require(:contacts_csv_file).permit(:data)
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class?(path)
    'active' if request.path == path
  end
end

app/views/contacts/csv_files/_form.html.erb
<%= form_with(model: contacts_csv_file) do |form| %>
  <% if contacts_csv_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contacts_csv_file.errors.count, "error") %> prohibited this file from being saved:</h2>

      <ul>
        <% contacts_csv_file.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="d-flex gap-3">
    <div class="field">
      <%= form.file_field :data, class: 'form-control', accept: 'text/csv' %>
    </div>

    <div class="actions align-self-end">
      <%= form.submit 'Submit', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/contacts/csv_files/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<div class="title-section d-flex justify-content-between">
  <h3 class="title">Listing Files</h3>
  <div class="actions">
    <%= link_to new_contacts_csv_file_path, class: 'btn btn-primary btn-sm' do %>
      <i class="bi bi-cloud-upload"></i> Upload File
    <% end %>
  </div>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>File Name</th>
      <th>Status</th>
      <th>User</th>
      <th>Uploaded at</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts_csv_files.each do |contacts_csv_file| %>
      <tr>
        <td><%= contacts_csv_file.name %></td>
        <td><%= contacts_csv_file.status %></td>
        <td><%= contacts_csv_file.user&.email %></td>
        <td><%= l contacts_csv_file.created_at, format: '%Y/%m/%d %H:%M' %></td>
        <td><%= link_to 'Show', contacts_csv_file %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/csv_files/new.html.erb
<div class="title-section">
  <h3 class="title">Upload a Contact File</h3>
</div>

<%= render 'form', contacts_csv_file: @contacts_csv_file %>

<%= link_to 'Back', contacts_csv_files_path %>

app/views/contacts/csv_files/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<div class="title-section">
  <h3 class="title">Uploaded File Details</h3>
</div>

<p>
  <strong>File:</strong>
  <a href="<%= url_for(@contacts_csv_file.data) %>">
    <%= @contacts_csv_file.name %>
  </a>
</p>

<div class="card">
  <div class="card-body">
    <p>
      <strong>Status:</strong>
      <%= @contacts_csv_file.status %>
    </p>

    <p>
      <strong>User:</strong>
      <%= @contacts_csv_file.user&.email %>
    </p>

    <p>
      <strong>Contacts Imported:</strong>
      <%= @contacts_csv_file.contacts.count %>
    </p>
  </div>
</div>

<div class="title-section">
  <h4 class="title">Contacts</h4>
</div>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Date of Birth</th>
    <th>Phone</th>
    <th>Imported By</th>
    <th>Address</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @contacts_csv_file.contacts.each do |contact| %>
    <tr>
      <td><%= contact.name %></td>
      <td><%= contact.email %></td>
      <td><%= l contact.dob, format: '%Y/%m/%d' %></td>
      <td><%= contact.phone %></td>
      <td><%= contact.user&.email %></td>
      <td><%= contact.address %></td>
      <td><%= link_to 'Show', contact %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', contacts_csv_files_path %>

app/views/contacts/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<div class="title-section">
  <h3 class="title">Listing Contacts</h3>
</div>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Date of Birth</th>
    <th>Phone</th>
    <th>Imported By</th>
    <th>Address</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @contacts.each do |contact| %>
    <tr>
      <td><%= contact.name %></td>
      <td><%= contact.email %></td>
      <td><%= l contact.dob, format: '%Y/%m/%d' %></td>
      <td><%= contact.phone %></td>
      <td><%= contact.user&.email %></td>
      <td><%= contact.address %></td>
      <td><%= link_to 'Show', contact %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/contacts/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<div class="title-section">
  <h3 class="title">Contact Details</h3>
</div>

<div class="card">
  <div class="card-body">
    <p>
      <strong>Name:</strong>
      <%= @contact.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @contact.email %>
    </p>

    <p>
      <strong>Date of Birth:</strong>
      <%= l @contact.dob, format: '%Y/%m/%d' %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @contact.phone %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @contact.address %>
    </p>

    <p>
      <strong>Imported by:</strong>
      <%= @contact.user&.email %>
    </p>
  </div>
</div>

<div class="title-section">
  <h4 class="title">Credit Cards</h4>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Last 4 Card Number</th>
      <th>Franchise</th>
      <th>Creation</th>
    </tr>
  </thead>
  <tbody>
  <% @contact.credit_cards.each do |credit_card| %>
    <tr>
      <td><%= credit_card.last_four %></td>
      <td><%= credit_card.franchise %></td>
      <td><%= l credit_card.created_at, format: :short %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', contacts_path %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><i class="bi bi-file-bar-graph"></i> ImportX</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="<%= current_page?(contacts_csv_files_path) ? 'nav-link active' : 'nav-link' %>"
             href="<%= contacts_csv_files_path %>">Uploaded Files</a>
        </li>
        <li class="nav-item">
          <a class="<%= current_page?(contacts_path) ? 'nav-link active' : 'nav-link' %>"
             href="<%= contacts_path %>">Contacts</a>
        </li>
      </ul>
      <div class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link"
               href="#">( <%= current_user.email %> )</a>
          </li>
          <li class="nav-item align-self-center">
            <%= link_to destroy_user_session_path, method: :delete, class: 'align-self-center btn btn-outline-danger btn-sm' do %>
              <i class="bi bi-arrow-left-square"></i> Sign Out
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactImporter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"
      />
  </head>

  <body>
    <%= render partial: 'layouts/nav' if current_user %>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>